### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by brokiem** [Bumbumkill/ShulkerBox#4]
shulkerbox kalo dihancurin gada item drop nya, malah disepir

**Comment by Bumbumkill** [comment]
Versi?

**Comment by Bumbumkill** [comment]
ShulkerBox Version: 
Pocketmine-MP version:

**Comment by brokiem** [comment]
PMPP 1.12.6 / 1.13.0

**Comment by Bumbumkill** [comment]
Please use latest pocketmine version.

https://github.com/pmmp/PocketMine-MP/releases/download/3.13.0/PocketMine-MP.phar
